[package]
name = "pyprjoxide"
version = "0.1.0"
edition = "2018"

[dependencies]
prjoxide = { path = "../prjoxide" }

[dependencies.pyo3]
version = "0.13.1"
features = ["extension-module"]

[dependencies.pythonize]
version = "0.13"

[lib]
name = "pyprjoxide"
crate-type = ["cdylib"]
